name: Build & publish images to the package registry for tags

on:
  release:
    types: [published]
  push:
    branches: [livekit]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to upload release asset
      packages: write
    steps:
      - name: Get current time
        id: current-time
        run: echo "unix_time=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Check it out
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@cf8514a65188af1d4f94f8c28a7a4153af1088ce
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - name: Install dependencies
        run: "yarn install"
      - name: Build
        run: "yarn run build"
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_APP_VERSION: ${{ github.event.release.tag_name || github.sha }}

      - name: Create Tarball
        env:
          TARBALL_VERSION: ${{ github.event.release.tag_name || github.sha }}
        run: |
          tar --numeric-owner --transform "s/dist/element-call-${TARBALL_VERSION}/" -cvzf element-call-${TARBALL_VERSION}.tar.gz dist

      - name: Upload
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: "./element-call-*.tar.gz"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@0f8c876bafbf5dbce05c36682ec68e9a0274a48a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short,event=branch
            type=semver,pattern=v{{version}}
            type=raw,value=latest-ci,enable={{is_default_branch}}
            type=raw,value=latest-ci_${{steps.current-time.outputs.unix_time}},enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55

      - name: Build and push Docker image
        uses: docker/build-push-action@9311bf5263ae5b36f3ec67aff768790c6e2344ad
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
