name: Run unit tests
on:
  pull_request: {}
  push:
    branches: [livekit, full-mesh]
jobs:
  vitest:
    name: Run vitest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Yarn cache
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Install dependencies
        run: "yarn install"
      - name: Vitest
        run: "yarn run test"
      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
